Repository brainupdaters/drlm, pull requests merged in 2023-02, with the labels that each got.

#205 Double check user deletion to skip error code 12
  usr/share/drlm/lib/install-functions.sh
Labels: bug

#206 some bugfix and new XML feature
  Makefile
  doc/drlm-release-notes.rst
  etc/drlm/rsyncd/rsyncd.motd
  etc/logrotate.d/drlm
  packaging/debian/changelog
  packaging/debian/drlm.dsc
  packaging/debian/postinst
  packaging/rpm/drlm.spec
  usr/sbin/drlm
  usr/share/drlm/conf/DHCP/config-DHCP.sh
  usr/share/drlm/conf/default.conf
  usr/share/drlm/conf/samples/client_PXE.cfg
  usr/share/drlm/conf/samples/client_data_only.cfg
  usr/share/drlm/conf/samples/client_default.cfg
  usr/share/drlm/conf/samples/client_default.drlm.cfg
  usr/share/drlm/conf/samples/client_incremental.cfg
  usr/share/drlm/conf/samples/client_incremental_data_only.cfg
  usr/share/drlm/lib/install-functions.sh
  usr/share/drlm/lib/report-functions.sh
  usr/share/drlm/www/drlm-api/drlm-api.go
  usr/share/drlm/www/drlm-proxy/drlm-proxy.go
  usr/share/drlm/www/drlm-send-error/configuration.go
  usr/share/drlm/www/drlm-send-error/drlm-send-error.go
  usr/share/drlm/www/drlm-send-error/logger.go
  var/lib/drlm/www/index.html
  var/lib/drlm/www/signin.html
Labels: bug, enhancement, NEW_feature

#208 Solve issue at runbackup umounting previous backups
  usr/share/drlm/lib/backup-functions.sh
Labels: bug, enhancement

#209 avoid hidden rsync errors
  doc/drlm-release-notes.rst
  packaging/debian/changelog
  packaging/rpm/drlm.spec
  usr/share/drlm/conf/samples/client_default.cfg
  usr/share/drlm/lib/install-functions.sh
Labels: bug
