Repository brainupdaters/drlm, pull requests merged in 2024-01, with the labels that each got.

#215 Added ability to adjust client configs upon migrations on rescue startup
  doc/drlm-release-notes.rst
  packaging/debian/changelog
  packaging/rpm/drlm.spec
  usr/share/drlm/conf/default.conf
  usr/share/drlm/lib/install-functions.sh
Labels: enhancement

#217 solved instclient errors at config stage due to permissions problem
  usr/share/drlm/lib/install-functions.sh
Labels: bug

#218 pre post runbackup bugfix and check client shell
  doc/drlm-release-notes.rst
  packaging/debian/changelog
  packaging/rpm/drlm.spec
  usr/share/drlm/backup/run/default/019_check_client_backup_reqs.sh
  usr/share/drlm/backup/run/default/099_pre_run_client_backup.sh
  usr/share/drlm/backup/run/default/119_post_run_client_backup.sh
  usr/share/drlm/client/inst/default/109_create_user_on_client.sh
  usr/share/drlm/conf/default.conf
Labels: bug, enhancement
