Repository brainupdaters/drlm, pull requests merged in 2024-02, with the labels that each got.

#219 rear tunning to avoid mac mapping on automatic recovery
  doc/drlm-release-notes.rst
  packaging/debian/changelog
  packaging/rpm/drlm.spec
  usr/share/drlm/conf/default.conf
  usr/share/drlm/lib/install-functions.sh
Labels: bug, enhancement

#221 New feature Telegram reporting
  doc/drlm-release-notes.rst
  packaging/debian/changelog
  packaging/rpm/drlm.spec
  usr/share/drlm/conf/default.conf
  usr/share/drlm/lib/report-functions.sh
Labels: NEW_feature

#222 Configurable error reporting message
  doc/drlm-release-notes.rst
  packaging/debian/changelog
  packaging/rpm/drlm.spec
  usr/share/drlm/backup/list/default/019_list_backups_by_client.sh
  usr/share/drlm/client/list/default/019_list_registered_clients.sh
  usr/share/drlm/conf/default.conf
  usr/share/drlm/lib/_input-output-functions.sh
  usr/share/drlm/lib/backup-functions.sh
  usr/share/drlm/lib/client-functions.sh
  usr/share/drlm/lib/job-functions.sh
  usr/share/drlm/lib/listbackup-workflow.sh
  usr/share/drlm/lib/listclient-workflow.sh
  usr/share/drlm/lib/listjob-workflow.sh
  usr/share/drlm/lib/listnetwork-workflow.sh
  usr/share/drlm/lib/network-functions.sh
Labels: enhancement, NEW_feature

#224 bugfix scheduled jobs and in non-interactive client installations
  doc/drlm-release-notes.rst
  packaging/debian/changelog
  packaging/rpm/drlm.spec
  usr/share/drlm/lib/install-functions.sh
  usr/share/drlm/lib/job-functions.sh
Labels: bug
