Repository brainupdaters/drlm, pull requests merged in 2024-09, with the labels that each got.

#241 drlm internal backups: configuration data and full dr
  etc/bash_completion.d/drlm_completions
  packaging/debian/postinst
  packaging/debian/preinst
  packaging/rpm/drlm.spec
  usr/share/drlm/client/inst/default/359_install_client_soft.sh
  usr/share/drlm/conf/rear-extra/usr/share/rear/drlm-extra/restorefiles/RSYNC/default/399_check_remote_backup_archive.sh
  usr/share/drlm/conf/rear-extra/usr/share/rear/drlm-extra/restorefiles/RSYNC/default/400_restore_rsync_backup.sh
  usr/share/drlm/conf/rear-extra/usr/share/rear/rescue/drlm-extra/010_merge_skeletons.sh
  usr/share/drlm/conf/samples/drlm_internal_config-data_default.cfg
  usr/share/drlm/conf/samples/drlm_internal_full_dr_iso.cfg
  usr/share/drlm/conf/samples/drlm_internal_full_dr_site_conf.cfg
  usr/share/drlm/lib/backup-functions.sh
  usr/share/drlm/lib/help-functions.sh
  usr/share/drlm/lib/install-functions.sh
  usr/share/drlm/lib/restore-workflow.sh
  usr/share/drlm/www/drlm-api/client.go
Labels: enhancement, NEW_feature

#243 fix postinstall errors
  packaging/debian/postinst
Labels: bug

#244 Solved issue with /bin/sh syntax in postinst
  packaging/debian/postinst
Labels: bug

#245 cleaned last found /bin/sh syntax error in postinst
  packaging/debian/postinst
Labels: bug

#247 New scan column for backups table in DB
  etc/bash_completion.d/drlm_completions
  usr/share/drlm/conf/DB/2.4.12_db_update.sql
  usr/share/drlm/lib/dbdrv/sqlite3-driver.sh
  usr/share/drlm/lib/help-functions.sh
  usr/share/drlm/lib/runbackup-workflow.sh
Labels: enhancement

#248 fix functions for new column from #PR 247
  etc/bash_completion.d/drlm_completions
  usr/share/drlm/conf/DB/drlm_sqlite_schema.sql
  usr/share/drlm/lib/backup-functions.sh
  usr/share/drlm/lib/dbdrv/sqlite3-driver.sh
Labels: bug

#250 fix issue #249
  usr/sbin/drlm-gitd-hook
  usr/share/drlm/client/inst/default/059_check_workflow_params.sh
Labels: bug

#251 fix issue 249
  usr/sbin/drlm-gitd-hook
Labels: bug

#253 fix some internal client stuff + rear install problem
  usr/share/drlm/client/del/default/019_check_client_exists.sh
  usr/share/drlm/lib/dbdrv/sqlite3-driver.sh
  usr/share/drlm/lib/install-functions.sh
Labels: bug
