Repository brainupdaters/drlm, pull requests merged in 2024-10, with the labels that each got.

#256 Change how internal client installation is done
  packaging/debian/postinst
  packaging/rpm/drlm.spec
  utils/drlm-build-install.sh
Labels: bug, enhancement

#258 Added Almalinux, Oracle Linux and Fedora distros support to client installation
  etc/drlm/cert/README.rst
  packaging/debian/postinst
  packaging/rpm/drlm.spec
  usr/share/drlm/backup/run/default/049_calc_dr_img_size.sh
  usr/share/drlm/client/inst/default/109_create_user_on_client.sh
  usr/share/drlm/client/inst/default/359_install_client_soft.sh
  usr/share/drlm/client/inst/default/459_start_services.sh
  usr/share/drlm/conf/default.conf
  usr/share/drlm/lib/backup-functions.sh
  usr/share/drlm/lib/install-functions.sh
Labels: enhancement

#259 bugfix in .ssh/id_rsa key location
  usr/share/drlm/client/inst/default/059_check_workflow_params.sh
  usr/share/drlm/lib/install-functions.sh
  utils/drlm-build-install.sh
Labels: bug

#260 Fixed client os version update in runbackup, cleanup comments in default.conf, etc.
  etc/drlm/cert/README.rst
  usr/share/drlm/backup/run/default/019_check_client_backup_reqs.sh
  usr/share/drlm/client/inst/default/109_create_user_on_client.sh
  usr/share/drlm/conf/default.conf
  usr/share/drlm/conf/samples/client_default.cfg
  usr/share/drlm/lib/install-functions.sh
Labels: bug
